---
- name: Install & Configure MetalLB (metallb)
  block:

    - name: Template MetalLB ConfigMap (metallb)
      import_tasks: template-metallb.yml

    - name: Configure Strict ARP on cluster (metallb)
      import_tasks: strictARP.yml

    - name: Configure and deploy MetalLB (metallb)
      import_tasks: install-metallb.yml

  when: '"True" in loadbalancer'