---
- name: Template MetalLB ConfigMap
  import_tasks: template-metallb.yml

- name: Configure Strict ARP on cluster
  import_tasks: strictARP.yml

- name: Configure and deploy MetalLB
  import_tasks: install-metallb.yml
