---
- name: Install rook (ceph)
  block:

    - name: Clone git repository to home directory
      git:
        repo: 'https://github.com/rook/rook.git'
        dest: $HOME/rook/rook-ceph
        version: v1.8.6
    
    - name: Create and apply crds, common and operator yaml configuration files
      shell: |
        cd $HOME/rook/rook-ceph/cluster/examples/kubernetes/ceph
        kubectl create -f crds.yaml -f common.yaml -f operator.yaml
      register: crds_common_operator_output

    - name: Debug create and apply of crds, common and operator yaml
      debug:
        msg: "{{ crds_common_operator_output.stdout }}"

    - name: Create and apply cluster.yaml configuration file
      shell: |
        cd $HOME/rook/rook-ceph/cluster/examples/kubernetes/ceph
        kubectl create -f cluster.yaml
      register: cluster_yaml_output

    - name: Debug create and apply of cluster.yaml
      debug:
        msg: "{{ cluster_yaml_output.stdout }}"

  when: '"true" in replicatestorage'
