---
#- name: Reload sysctl
#  import_tasks: sysctl-handler.yaml
  
- name: Reload UFW
  import_tasks: ufw-handler.yaml
  
- name: Reload Docker daemon and systemd, and enable Docker on boot
  import_tasks: docker-handler.yaml

- name: Reload haproxy with systemd
  import_tasks: haproxy-handler.yml

- name: Reload containerd with systemd
  import_tasks: containerd-handler.yml
