---
- name: Calico
  block:
    - name: Get Calico config yaml
      get_url:
        url: https://docs.projectcalico.org/manifests/calico.yaml
        dest: /home/kube/calico.yaml

    - name: Apply Calico yaml
      shell: kubectl apply -f calico.yaml
      register: install_calico_output

    - name: Debug install calico output
      debug:
        msg: "{{ install_calico_output.stdout }}"
  when: '"calico" in networkplugin'

- name: Weave
  block:
    - name: Install Weave
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
      register: install_weave_output

    - name: Debug install weave output
      debug:
        msg: "{{ install_weave_output.stdout }}"
  when: '"weave" in networkplugin'

- name: Flannel
  block:
    - name: Install Flannel
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      register: install_flannel_output

    - name: Debug install flannel output
      debug:
        msg: "{{ install_flannel_output.stdout }}"
  when: '"flannel" in networkplugin'

- name: Cilium
  block:
    - name: Install Cilium
      shell: |
        curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
        sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
        sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
        rm cilium-linux-amd64.tar.gz{,.sha256sum}
        /usr/local/bin/cilium install
      register: install_cilium_output

    - name: Debug install cilium output
      debug:
        msg: "{{ install_cilium_output.stdout }}"
  when: '"remove-this" in networkplugin'

- name: Cilium2
  block:
    - name: Install Cilium2
      shell: kubectl apply -f https://raw.githubusercontent.com/nwebb11/ready8s/v2.3.2/roles/buildcluster/files/install-cilium.yaml
      register: install_cilium2_output

    - name: Debug install cilium2 output
      debug:
        msg: "{{ install_cilium2_output.stdout }}"
  when: '"cilium2" in networkplugin'

- name: Cilium-helm
  block:
    - name: Install Helm
      shell: |
        curl https://baltocdn.com/helm/signing.asc | apt-key add -
        apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
        apt-get update -y
        apt-get install helm -y
      register: install_helm_output

    - name: Debug install helm output
      debug:
        msg: "{{ install_helm_output.stdout }}"

    - name: Install Cilium-helm
      shell: |
        helm repo add cilium https://helm.cilium.io/
        helm install cilium cilium/cilium --version 1.11.4 --namespace kube-system
      register: install_cilium_helm_output

    - name: Debug install cilium-helm output
      debug:
        msg: "{{ install_cilium_helm_output.stdout }}"
  when: '"helm" in networkplugin'