---
- name: Add overlay and br_netfilter to containerd module
  copy:
    dest: "/etc/modules-load.d/containerd.conf"
    content: |
      overlay
      br_netfilter
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Run modprobe
  shell: |
    modprobe overlay
    modprobe br_netfilter
  become: yes

- name: Configure iptables
  copy:
    dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Apply sysctl parameters without reboot
  shell: sysctl --system
  become: yes

- name: Install required packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - git
    state: present
  become: yes
  retries: 5
  delay: 10

#- name: Add docker GPG key
#  apt_key:
#    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
#    state: present
#  become: yes
#  retries: 5
#  delay: 10

#- name: Add docker repository
#  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} $(lsb_release -cs) stable"
#  become: yes
#  retries: 5
#  delay: 10

- name: Add Docker GPG key (new)
  shell: curl -fsSL https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes

- name: Add Docker repository (new)
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution|lower }} $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: yes

- name: Update package index
  apt:
    update_cache: yes
  become: yes
  retries: 5
  delay: 10

- name: Install containerd
  apt:
    name: containerd.io
    state: latest
  become: yes
  retries: 5
  delay: 10

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Generate containerd config file
  shell: |
    containerd config default | tee /etc/containerd/config.toml
    systemctl restart containerd
  become: yes

- name: Edit containerd config file
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^            SystemdCgroup = false'
    line: '            SystemdCgroup = true'
    backrefs: yes
  notify: Restart containerd
