---
- name: Create k8s.conf under sysctl
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
    owner: root
    group: root
    mode: '0644'

- name: Reload sysctl
  shell: sysctl --system
