---
- name: Install needed packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    state: present

- name: Add Google GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  retries: 5
  delay: 10

- name: Add K8s repository
  copy:
    dest: "/etc/apt/sources.list.d/kubernetes.list"
    content: |
      deb https://apt.kubernetes.io/ kubernetes-xenial main
    owner: root
    group: root
    mode: '0644'

- name: Check package index and update cache
  apt:
    update_cache: yes

- name: Install K8s 1.25.0 (Test Only)
  block:
    - name: Install K8s 1.25.0 packages (Test Only)
      apt:
        pkg:
        - kubelet=1.25.0-00
        - kubeadm=1.25.0-00
        - kubectl=1.25.0-00
        state: present
  when: '"1.25.0" in k8sversion'

- name: Install K8s 1.25.1
  block:
    - name: Install K8s 1.25.1 packages
      apt:
        pkg:
        - kubelet=1.25.1-00
        - kubeadm=1.25.1-00
        - kubectl=1.25.1-00
        state: present
  when: '"1.25.1" in k8sversion'

- name: Install K8s 1.25.2
  block:
    - name: Install K8s 1.25.2 packages
      apt:
        pkg:
        - kubelet=1.25.2-00
        - kubeadm=1.25.2-00
        - kubectl=1.25.2-00
        state: present
  when: '"1.25.2" in k8sversion'

- name: Install K8s 1.25.3
  block:
    - name: Install K8s 1.25.3 packages
      apt:
        pkg:
        - kubelet=1.25.3-00
        - kubeadm=1.25.3-00
        - kubectl=1.25.3-00
        state: present
  when: '"1.25.3" in k8sversion'

- name: Install K8s 1.25.4
  block:
    - name: Install K8s 1.25.4 packages
      apt:
        pkg:
        - kubelet=1.25.4-00
        - kubeadm=1.25.4-00
        - kubectl=1.25.4-00
        state: present
  when: '"1.25.4" in k8sversion'

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
