---
- name: Apply UFW profile for master nodes (setup-k8smaster)
  block:

    - name: Apply UFW profile & reload (setup-k8smaster)
      ufw:
        rule: allow
        name: MasterNodeProfile-TCP
      notify: Reload UFW

  when: '"True" in ufwfirewall'