---
- name: Apply UFW profile for worker nodes (setup-k8sworker)
  block:

    - name: Apply UFW profile & reload (setup-k8sworker)
      ufw:
        rule: allow
        name: WorkerNodeProfile-TCP
      notify: Reload UFW

  when: '"True" in ufwfirewall'